<?php

declare(strict_types=1);

namespace App\Cost\Services;

use App\Cost\Data\CostEntry;
use App\Enums\CostActorKind;
use App\Enums\CostCategory;
use Illuminate\Support\Carbon;

/**
 * What one unit of work spent (docs/COST.md §5).
 *
 * ===========================================================================
 *  This class replaces App\Domain\Recommendations\Services\CostMeter, which had
 *  three bugs. They are worth naming, because each one is a trap the next
 *  implementation would fall into again.
 * ===========================================================================
 *
 * 1. IT WAS A SINGLETON, AND `reset()` HAD NO CALLERS. Fine in a web request, which
 *    dies at the end. Not fine in a Horizon worker, which is a long-lived process:
 *    the meter accumulated across every job it ever ran, so the tenth job's trace
 *    carried the first nine jobs' costs. It is `scoped()` now — Laravel flushes
 *    scoped instances between queued jobs — and the flush is explicit besides.
 *
 * 2. THE TOKEN SPLIT WAS DESTROYED AT CAPTURE. `recordLlmTokens($in + $out)`, one
 *    line after extracting them separately. Gemini prices input, output and cached
 *    input at three different rates, so a summed count cannot be turned back into
 *    money — the data needed to compute the bill was thrown away immediately before
 *    it was needed. `recordLlm()` keeps all three, plus the model, because the rate
 *    depends on the model too.
 *
 * 3. THE COST IT REPORTED WAS STRUCTURALLY ZERO. `recommendations.cost.llm_tokens`
 *    was written by RankSession on the SERVE path — but the voice is generated by a
 *    job, dispatched and never awaited (correctly: a user waiting on a model is a
 *    user watching a spinner). The tokens were therefore spent later, in another
 *    process, and landed in a meter nobody read. Cost is ASYNCHRONOUS and
 *    MULTI-ACTOR, so it cannot be written once at serve time; it has to accrete to
 *    correlation ids after the fact. Hence the ledger, and hence the `on*()` context
 *    setters below: the job re-establishes the correlation the request could not.
 *
 * The meter itself stays deliberately stupid — it accumulates entries in memory and
 * knows nothing about prices, Redis or SQL. {@see CostLedger} does the writing, once
 * per unit of work.
 */
final class CostMeter
{
    /** @var list<CostEntry> */
    private array $entries = [];

    private CostActorKind $actorKind = CostActorKind::User;

    private ?int $userId = null;

    private ?string $tripId = null;

    private ?string $sessionId = null;

    private ?string $recommendationId = null;

    private ?string $opportunityId = null;

    private ?string $regionKey = null;

    private ?string $h3Cell = null;

    /*
    |--------------------------------------------------------------------------
    | Context — who this work is for
    |--------------------------------------------------------------------------
    |
    | Set once, at the boundary: the HTTP middleware from the request, the job
    | middleware from the job's own payload. Nothing deeper in the stack should have
    | to thread a user id through six constructors to record a token count.
    */

    public function actingAs(CostActorKind $kind, ?int $userId = null): self
    {
        $this->actorKind = $kind;
        $this->userId = $userId;

        return $this;
    }

    public function onTrip(?string $tripId): self
    {
        $this->tripId = $tripId;

        return $this;
    }

    public function onSession(?string $sessionId): self
    {
        $this->sessionId = $sessionId;

        return $this;
    }

    public function onRecommendation(?string $recommendationId): self
    {
        $this->recommendationId = $recommendationId;

        return $this;
    }

    public function onOpportunity(?string $opportunityId): self
    {
        $this->opportunityId = $opportunityId;

        return $this;
    }

    public function onRegion(?string $regionKey): self
    {
        $this->regionKey = $regionKey;

        return $this;
    }

    public function atCell(?string $h3Cell): self
    {
        $this->h3Cell = $h3Cell;

        return $this;
    }

    /*
    |--------------------------------------------------------------------------
    | Recording
    |--------------------------------------------------------------------------
    */

    public function record(CostEntry $entry): void
    {
        /*
         * Stamp WHO THIS WAS FOR now, not at flush.
         *
         * The context used to be read once, at flush, and applied to every entry alike —
         * so a request that names a different card partway through (the Stage-B route
         * lookup for item 3, say) mis-attributed everything before it, and the last id set
         * won. In practice the ledger could not answer "what did this card cost?" at all:
         * the emulator asked, and every item came back zero.
         *
         * Cost is caused at the moment it is recorded. This is that moment.
         */
        $this->entries[] = $entry->correlatedWith($this->context());
    }

    /**
     * A generation. All three token classes, or the money is not computable (bug 2).
     *
     * `$cached` means the OUTPUT came from our 30-day evidence-bundle cache and no
     * request was made at all — the tokens passed here are then what the call would
     * have consumed, which is exactly what makes the saving measurable.
     */
    public function recordLlm(
        string $model,
        int $inputTokens,
        int $outputTokens,
        int $cachedInputTokens = 0,
        ?string $promptVersion = null,
        bool $cached = false,
    ): void {
        $this->record(new CostEntry(
            category: CostCategory::Llm,
            vendor: 'gemini',
            resource: $model,
            host: 'generativelanguage.googleapis.com',
            model: $model,
            promptVersion: $promptVersion,
            inputTokens: $inputTokens,
            outputTokens: $outputTokens,
            cachedInputTokens: $cachedInputTokens,
            calls: $cached ? 0 : 1,
            cached: $cached,
            occurredAt: Carbon::now(),
        ));
    }

    /**
     * One outbound HTTP call, recorded by the global client hook so that a paid API
     * added by someone who never read this file still shows up (AppServiceProvider).
     *
     * The host is all we get, and — importantly — all we WANT: the full URI carries
     * query strings, and ours carry coordinates. Writing one here would re-open ROPA
     * finding B1 in a table we designed ourselves.
     */
    public function recordApiCall(string $host, string $vendor, ?string $resource): void
    {
        if ($resource === null) {
            return;   // metered elsewhere with better data (the LLM host)
        }

        $this->record(new CostEntry(
            category: CostCategory::Api,
            vendor: $vendor,
            resource: $resource,
            host: $host,
            calls: 1,
            occurredAt: Carbon::now(),
        ));
    }

    /** A cache hit on a paid API: cost nothing, would have cost something. */
    public function recordApiCacheHit(string $host, string $vendor, ?string $resource): void
    {
        if ($resource === null) {
            return;
        }

        $this->record(new CostEntry(
            category: CostCategory::Api,
            vendor: $vendor,
            resource: $resource,
            host: $host,
            calls: 1,
            cached: true,
            occurredAt: Carbon::now(),
        ));
    }

    /**
     * The compute row: units, never money (COST.md §2.1).
     *
     * CPU time, not wall time — wall time on a request that spent four seconds
     * waiting for Google tells you about Google, not about the server we rent.
     */
    public function recordCompute(string $resource, int $cpuMs, int $peakMemKb): void
    {
        $this->record(new CostEntry(
            category: CostCategory::Compute,
            vendor: 'self',
            resource: $resource,
            cpuMs: $cpuMs,
            peakMemKb: $peakMemKb,
            occurredAt: Carbon::now(),
        ));
    }

    /*
    |--------------------------------------------------------------------------
    | Reading & draining
    |--------------------------------------------------------------------------
    */

    /** @return list<CostEntry> */
    public function entries(): array
    {
        return $this->entries;
    }

    public function actorKind(): CostActorKind
    {
        return $this->actorKind;
    }

    /** @return array<string, mixed> the correlation context, as ledger columns */
    public function context(): array
    {
        return [
            'actor_kind' => $this->actorKind->value,
            'user_id' => $this->userId,
            'trip_id' => $this->tripId,
            'session_id' => $this->sessionId,
            'recommendation_id' => $this->recommendationId,
            'opportunity_id' => $this->opportunityId,
            'region_key' => $this->regionKey,
            'h3_cell' => $this->h3Cell,
            // Reserved for the Phase 3 chat (COST.md §5.1). Nothing writes it yet.
            'conversation_id' => null,
        ];
    }

    public function userId(): ?int
    {
        return $this->userId;
    }

    /**
     * Forget who this work was for, mid-flight.
     *
     * Exists for exactly one caller, and it is not a hypothetical: the request that
     * ERASES an account is itself a metered request, and its cost row is written by the
     * terminating middleware — i.e. AFTER the account is gone. Without this, erasure
     * nulls every historical row and then the flush cheerfully writes a fresh one
     * carrying the id of the user we just deleted. The ledger would resurrect the person
     * it had erased, on every single deletion.
     *
     * The erasure test caught this, which is precisely what it was written to do.
     */
    public function forgetUser(): void
    {
        $this->userId = null;
        $this->tripId = null;
        $this->sessionId = null;
        $this->recommendationId = null;
        $this->opportunityId = null;
        $this->h3Cell = null;
    }

    /**
     * Hand over the entries and forget them.
     *
     * Draining rather than resetting is the fix for bug 1 with teeth: after a flush
     * there is nothing left to leak into the next job, whether or not the container
     * scoping behaves the way we think it does. Two mechanisms, one guarantee.
     *
     * @return list<CostEntry>
     */
    public function drain(): array
    {
        $entries = $this->entries;
        $this->entries = [];

        return $entries;
    }

    /*
    |--------------------------------------------------------------------------
    | Serve-path summary (the old, narrow number)
    |--------------------------------------------------------------------------
    |
    | RankSession still writes a cost blob onto the recommendation trace. It is
    | SERVE-PATH ONLY and always will be — the voice tokens are spent later, in the
    | voice job (bug 3). The blob is a latency/fan-out record, not a bill; the bill is
    | the ledger. Kept, because the trace should say what the serve path did.
    */

    public function apiCalls(): int
    {
        return array_sum(array_map(
            static fn (CostEntry $e): int => $e->category === CostCategory::Api ? $e->calls : 0,
            $this->entries,
        ));
    }

    /** @return array<string, int> */
    public function byHost(): array
    {
        $byHost = [];

        foreach ($this->entries as $entry) {
            if ($entry->category !== CostCategory::Api || $entry->host === null) {
                continue;
            }

            $byHost[$entry->host] = ($byHost[$entry->host] ?? 0) + $entry->calls;
        }

        return $byHost;
    }
}
